# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_wkt_area <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_area`, wkt, strategy)
}

rcpp_wkt_centroid <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_centroid`, wkt)
}

rcpp_wkt_convex_hull <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_convex_hull`, wkt)
}

rcpp_wkt_distance_cartesian <- function(wktFrom, wktTo) {
    .Call(`_boostgeometry_rcpp_wkt_distance_cartesian`, wktFrom, wktTo)
}

rcpp_wkt_distance_spherical <- function(wktFrom, wktTo) {
    .Call(`_boostgeometry_rcpp_wkt_distance_spherical`, wktFrom, wktTo)
}

rcpp_wkt_distance_geographic <- function(wktFrom, wktTo) {
    .Call(`_boostgeometry_rcpp_wkt_distance_geographic`, wktFrom, wktTo)
}

rcpp_wkt_is_empty <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_is_empty`, wkt, strategy)
}

rcpp_wkt_is_simple <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_is_simple`, wkt, strategy)
}

rcpp_wkt_is_valid <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_is_valid`, wkt, strategy)
}

rcpp_wkt_length_cartesian <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_length_cartesian`, wkt)
}

rcpp_wkt_length_spherical <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_length_spherical`, wkt)
}

rcpp_wkt_length_geographic <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_length_geographic`, wkt)
}

rcpp_wkt_num_geometries <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_num_geometries`, wkt)
}

rcpp_wkt_num_interior_rings <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_num_interior_rings`, wkt)
}

rcpp_wkt_num_points <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_num_points`, wkt)
}

rcpp_wkt_num_segments <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_num_segments`, wkt)
}

