# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_wkt_area <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_area`, wkt, strategy)
}

rcpp_wkt_centroid <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_centroid`, wkt)
}

