# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_wkt_convex_hull <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_convex_hull`, wkt)
}

rcpp_wkt_envelope <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_envelope`, wkt, strategy)
}

rcpp_wkt_perimeter_cartesian <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_perimeter_cartesian`, wkt)
}

rcpp_wkt_perimeter_spherical <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_perimeter_spherical`, wkt)
}

rcpp_wkt_perimeter_geographic <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_perimeter_geographic`, wkt)
}

rcpp_wkt_simplify <- function(wkt, strategy, distance) {
    .Call(`_boostgeometry_rcpp_wkt_simplify`, wkt, strategy, distance)
}

rcpp_wkt_unique <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_unique`, wkt, strategy)
}

